import type { CustomAdapter } from "@better-auth/core/db/adapter";
import { buildSchemaDefinition } from "./schema/build-schema";

/**
 * Powers the Better Auth CLI's `generate` command. Mongoose has no DDL to
 * migrate, so instead of a migration file this emits the Mongoose Schema
 * definitions the adapter would build by default — a starting point for
 * consumers who want to eject to fully custom schemas beyond what the
 * merge-based `schemas` option supports.
 */
export function makeCreateSchema(): NonNullable<CustomAdapter["createSchema"]> {
  return async ({ file, tables }) => {
    const lines = [
      "// Auto-generated by better-auth-mongoose's `npx @better-auth/cli generate`.",
      "// Eject this file and pass the resulting schemas via mongooseAdapter's",
      "// `schemas` option if you need full control beyond schema merging.",
      'import { Schema } from "mongoose";',
      "",
    ];

    for (const [name, table] of Object.entries(tables)) {
      const definition = buildSchemaDefinition(table.fields);
      const fieldLines = Object.entries(definition).map(([field, def]) => {
        const opts = def as Record<string, unknown>;
        const type =
          opts.type === String
            ? "String"
            : opts.type === Number
              ? "Number"
              : opts.type === Boolean
                ? "Boolean"
                : opts.type === Date
                  ? "Date"
                  : "Schema.Types.ObjectId";
        const rest = { ...opts };
        delete rest.type;
        const restEntries = Object.entries(rest)
          .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
          .join(", ");
        return `    ${field}: { type: ${type}${restEntries ? `, ${restEntries}` : ""} },`;
      });

      lines.push(`export const ${name}Schema = new Schema({`, ...fieldLines, "});", "");
    }

    return { code: lines.join("\n"), path: file ?? "./better-auth-mongoose-schemas.ts" };
  };
}
