import type { CustomAdapter } from "@better-auth/core/db/adapter";
import { buildSchemaDefinition, TYPE_MAP } from "./schema/build-schema";

// The generated file only imports `Schema`, so a scalar `type` constructor
// must be printed as the identifier it's assigned to (e.g. `String`), not
// `Schema.Types.ObjectId` — derived from TYPE_MAP so this can never drift
// out of sync with the types buildSchemaDefinition actually produces.
const TYPE_NAMES = new Map<unknown, string>(
  Object.values(TYPE_MAP).map((ctor) => [ctor, ctor.name]),
);

/**
 * Powers the Better Auth CLI's `generate` command. Mongoose has no DDL to
 * migrate, so instead of a migration file this emits the Mongoose Schema
 * definitions the adapter would build by default — a starting point for
 * consumers who want to eject to fully custom schemas beyond what the
 * merge-based `schemas` option supports.
 */
export function makeCreateSchema(): NonNullable<CustomAdapter["createSchema"]> {
  return async ({ file, tables }) => {
    const lines = [
      "// Auto-generated by better-auth-mongoose's `npx @better-auth/cli generate`.",
      "// Eject this file and pass the resulting schemas via mongooseAdapter's",
      "// `schemas` option if you need full control beyond schema merging.",
      'import { Schema } from "mongoose";',
      "",
    ];

    for (const [name, table] of Object.entries(tables)) {
      const definition = buildSchemaDefinition(table.fields);
      const fieldLines = Object.entries(definition).map(([field, def]) => {
        const opts = def as Record<string, unknown>;
        const type = TYPE_NAMES.get(opts.type) ?? "Schema.Types.ObjectId";
        const rest = { ...opts };
        delete rest.type;
        const restEntries = Object.entries(rest)
          // A function-typed defaultValue (e.g. Better Auth's own
          // `createdAt: { defaultValue: () => new Date() }`) must be inlined
          // as source via .toString() — JSON.stringify(fn) is `undefined`,
          // which would otherwise silently emit `default: undefined` and
          // drop the generator entirely from the ejected file.
          .map(([k, v]) => `${k}: ${typeof v === "function" ? v.toString() : JSON.stringify(v)}`)
          .join(", ");
        return `    ${field}: { type: ${type}${restEntries ? `, ${restEntries}` : ""} },`;
      });

      lines.push(`export const ${name}Schema = new Schema({`, ...fieldLines, "});", "");
    }

    return { code: lines.join("\n"), path: file ?? "./better-auth-mongoose-schemas.ts" };
  };
}
